resources:
  pipelines:
    sales_pipeline:
      name: sales_dlt_prod
      target: sales_prod
      catalog: sales
      serverless: true

      libraries:
        - file:
            path: ../../src/bronze/ingest_sales.py
        - file:
            path: ../../src/silver/clean_sales.py
        - file:
            path: ../../src/gold/agg_sales.py

      configuration:
        pipeline.mode: "production"
        env: prod
        s3.raw.path: s3://sales-lakehouse-vidya/prod/raw/sales/
